import type { AlignmentReport } from "./types";

export const demoReport: AlignmentReport = {
  overall_score: 91,
  verdict: "Aligned",
  master_file: "master-template.docx",
  document_file: "project-report-v3.docx",
  generated_at: new Date().toISOString(),
  categories: [
    { key: "structure", label: "Structure", score: 100 },
    { key: "typography", label: "Typography", score: 94 },
    { key: "layout", label: "Layout", score: 87 },
    { key: "formatting", label: "Formatting", score: 96 },
    { key: "visual", label: "Visual", score: 93 },
    { key: "semantic", label: "Semantic", score: 98 },
  ],
  master_profile: {
    file_name: "master-template.docx",
    groups: [
      {
        group: "Document Structure",
        items: [
          "Title",
          "Introduction",
          "Objectives",
          "Methodology",
          "Results",
          "Conclusion",
          "References",
        ],
      },
      {
        group: "Typography",
        items: ["Arial", "Body: 11 pt", "Heading 1: 16 pt", "Heading 2: 14 pt", "Bold headings"],
      },
      {
        group: "Layout",
        items: ["A4", "1-inch margins", "Justified paragraphs", "1.15 line spacing"],
      },
      {
        group: "Formatting",
        items: [
          "Heading numbering",
          "Consistent spacing",
          "Centered figures",
          "Caption below figures",
        ],
      },
      { group: "Language", items: ["British English", "Defined terminology"] },
      { group: "Colors", items: ["Heading color", "Table styling", "Accent color"] },
      { group: "Assets", items: ["Images", "Tables"] },
    ],
  },
  changes: [
    {
      id: "chg_001",
      category: "structure",
      section: "Title",
      master: "MachineShield Edge",
      document: "MachineShield",
      action: "modify",
      change: 'Change "MachineShield" → "MachineShield Edge"',
      severity: "high",
      reason: "Title does not carry the full product name used in the Master",
      confidence: 0.94,
    },
    {
      id: "chg_002",
      category: "structure",
      section: "Introduction",
      master: "Introduction",
      document: "—",
      action: "add",
      change: 'Add an "Introduction" section after the Title',
      severity: "high",
      reason: "Required Master section is absent",
      confidence: 0.98,
    },
    {
      id: "chg_003",
      category: "structure",
      section: "Objectives",
      master: "Objectives",
      document: "Project Goals",
      action: "modify",
      change: 'Rename "Project Goals" → "Objectives"',
      severity: "medium",
      reason: "Section naming does not follow the Master pattern",
      confidence: 0.96,
    },
    {
      id: "chg_004",
      category: "structure",
      section: "Methodology",
      master: "Section 3 (after Objectives)",
      document: "Section 2 (before Objectives)",
      action: "move",
      change: 'Move "Methodology" below "Objectives"',
      severity: "medium",
      reason: "Section order differs from the Master hierarchy",
      confidence: 0.91,
    },
    {
      id: "chg_005",
      category: "typography",
      section: "Body text",
      master: "Arial, 11 pt, justified",
      document: "Times New Roman, 12 pt, left",
      action: "modify",
      change: "Change body text to Arial, 11 pt, justified",
      severity: "high",
      reason: "Body typography does not match the Master profile",
      confidence: 0.99,
    },
    {
      id: "chg_006",
      category: "visual",
      section: "Figure 1",
      master: "Center aligned, caption below",
      document: "Left aligned, caption below",
      action: "modify",
      change: "Move Figure 1 to center alignment",
      severity: "low",
      reason: "Figures are centered throughout the Master",
      confidence: 0.88,
    },
    {
      id: "chg_007",
      category: "semantic",
      section: "Requirements",
      master: "The system SHALL authenticate users before access.",
      document: "The system MAY authenticate users before access.",
      action: "modify",
      change: 'Change "MAY" → "SHALL"',
      severity: "high",
      reason: "Requirement strength is weakened relative to the Master",
      confidence: 0.97,
    },
    {
      id: "chg_008",
      category: "semantic",
      section: "Monitoring",
      master: "The system shall provide real-time monitoring of machine conditions.",
      document: "The system provides machine monitoring.",
      action: "add",
      change: 'Add the missing requirement covering "real-time monitoring of machine conditions"',
      severity: "medium",
      reason: "Master concept is only partially covered",
      confidence: 0.9,
    },
    {
      id: "chg_009",
      category: "formatting",
      section: "Appendix",
      master: "—",
      document: "Appendix A",
      action: "remove",
      change: 'Remove the "Appendix A" section',
      severity: "low",
      reason: "Section has no counterpart in the Master pattern",
      confidence: 0.72,
    },
    {
      id: "chg_010",
      category: "structure",
      section: "Conclusion",
      master: "Conclusion",
      document: "Conclusion",
      action: "none",
      change: "No change required",
      severity: "none",
      reason: "Matches the Master pattern",
      confidence: 1,
    },
    {
      id: "chg_011",
      category: "semantic",
      section: "Terminology",
      master: "Artificial Intelligence",
      document: "Artificial inteligence",
      action: "modify",
      change: 'Change "inteligence" → "intelligence"',
      severity: "medium",
      reason: "Defined Master terminology is misspelled",
      confidence: 0.99,
    },
  ],
};
